name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build
        env:
          GATSBY_CONTACT_SERVICE_ID: ${{secrets.GATSBY_CONTACT_SERVICE_ID}}
          GATSBY_CONTACT_TEMPLATE_ID: ${{secrets.GATSBY_CONTACT_TEMPLATE_ID}}
          GATSBY_CONTACT_USER_ID: ${{secrets.GATSBY_CONTACT_USER_ID}}
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
        run: |
          npm install
          npm run build

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://${{ secrets.BUCKET_NAME}} --delete
